//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedTest.Practice.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedTest.Practice.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _1_result {
            get {
                object obj = ResourceManager.GetObject("_1_result", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _2_result {
            get {
                object obj = ResourceManager.GetObject("_2_result", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _3_result {
            get {
                object obj = ResourceManager.GetObject("_3_result", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в систему адаптивного обучения по дисциплине &apos;Информационные технологии&apos;. Продолжите свое обучение.
        /// </summary>
        internal static string ContinueMessage {
            get {
                return ResourceManager.GetString("ContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docx.
        /// </summary>
        internal static string DocExtenstion {
            get {
                return ResourceManager.GetString("DocExtenstion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете переходить к следующей главе..
        /// </summary>
        internal static string GoToNextTheoryMessage {
            get {
                return ResourceManager.GetString("GoToNextTheoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете переходить к следующей главе, но вам необходима консультация по данной теме у преподавателя..
        /// </summary>
        internal static string GoToNextTheoryWithWarningMessage {
            get {
                return ResourceManager.GetString("GoToNextTheoryWithWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/logo.jpg.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        internal static string PdfExtension {
            get {
                return ResourceManager.GetString("PdfExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша оценка - {0}..
        /// </summary>
        internal static string PointMessage {
            get {
                return ResourceManager.GetString("PointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы завершили контрольную работу. Потраченное время {0}..
        /// </summary>
        internal static string PracticeCompleteTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeCompleteTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению вы допустили ошибки({0} ошибки)..
        /// </summary>
        internal static string PracticeFailedTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeFailedTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем,ошибок нет..
        /// </summary>
        internal static string PracticeSuccessTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeSuccessTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы набрали {0}%..
        /// </summary>
        internal static string TestCompleteTemplateMessage {
            get {
                return ResourceManager.GetString("TestCompleteTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам необходимо лучше изучить теорию..
        /// </summary>
        internal static string TestFailedMessage {
            get {
                return ResourceManager.GetString("TestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляю, вы завершили курс по дисциплине “Информационные технологии”, ваши результаты:.
        /// </summary>
        internal static string UserCompleteTheoryMessage {
            get {
                return ResourceManager.GetString("UserCompleteTheoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты выполнения тестов по главам.
        /// </summary>
        internal static string UserTheoryResultMessage {
            get {
                return ResourceManager.GetString("UserTheoryResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в систему адаптивного обучения по дисциплине &apos;Информационные технологии&apos;. Для начала необходимо пройти входное тестирование.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
