//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedTest.Practice.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedTest.Practice.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в систему адаптивного обучения по дисциплине &apos;Информационные технологии&apos;. Продолжите свое обучение.
        /// </summary>
        internal static string ContinueMessage {
            get {
                return ResourceManager.GetString("ContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на docx.
        /// </summary>
        internal static string DocExtenstion {
            get {
                return ResourceManager.GetString("DocExtenstion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можете переходить к следующей главе..
        /// </summary>
        internal static string GoToNextTheoryMessage {
            get {
                return ResourceManager.GetString("GoToNextTheoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можете переходить к следующей главе, но вам необходима консультация по данной теме у преподавателя..
        /// </summary>
        internal static string GoToNextTheoryWithWarningMessage {
            get {
                return ResourceManager.GetString("GoToNextTheoryWithWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content/logo.jpg.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pdf.
        /// </summary>
        internal static string PdfExtension {
            get {
                return ResourceManager.GetString("PdfExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша оценка - {0}..
        /// </summary>
        internal static string PointMessage {
            get {
                return ResourceManager.GetString("PointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы завершили контрольную работу. Потраченное время {0}..
        /// </summary>
        internal static string PracticeCompleteTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeCompleteTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению вы допустили ошибки({0} ошибки)..
        /// </summary>
        internal static string PracticeFailedTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeFailedTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поздравляем,ошибок нет..
        /// </summary>
        internal static string PracticeSuccessTemplateMessage {
            get {
                return ResourceManager.GetString("PracticeSuccessTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] result {
            get {
                object obj = ResourceManager.GetObject("result", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы набрали {0}%..
        /// </summary>
        internal static string TestCompleteTemplateMessage {
            get {
                return ResourceManager.GetString("TestCompleteTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам необходимо лучше изучить теорию..
        /// </summary>
        internal static string TestFailedMessage {
            get {
                return ResourceManager.GetString("TestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поздравляю, вы завершили курс по дисциплине “Информационные технологии”, ваши результаты:.
        /// </summary>
        internal static string UserCompleteTheoryMessage {
            get {
                return ResourceManager.GetString("UserCompleteTheoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты выполнения тестов по главам.
        /// </summary>
        internal static string UserTheoryResultMessage {
            get {
                return ResourceManager.GetString("UserTheoryResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в систему адаптивного обучения по дисциплине &apos;Информационные технологии&apos;. Для начала необходимо пройти входное тестирование.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
