// <auto-generated />
namespace AdvancedTest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertPracticeParts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertPracticeParts));
        
        string IMigrationMetadata.Id
        {
            get { return "201810101556135_InsertPracticeParts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
